const mongoose = require('mongoose');

const ParticipantSchema = new mongoose.Schema({
    //using autogenerated id
    _id: { type: mongoose.Schema.Types.ObjectId, auto: true }, 
  });

  
const Participant = mongoose.model("Participant", ParticipantSchema);
module.exports = Participant; 
  